DROP DATABASE IF EXISTS history;
CREATE DATABASE history;
USE history;
CREATE TABLE history (
Id INT primary KEY,
Name VARCHAR(255),
Birth INT,
Death INT,
Width INT,
Category VARCHAR(255),
Location VARCHAR(255) 
);

INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(1,"Marilyn Monroe ",1926,1962,180,"Entertainer","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(2,"Abraham Lincoln ",1809,1865,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(3,"Mother Teresa ",1910,1997,"Religion","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(4,"John F. Kennedy ",1917,1963,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(5,"Martin Luther King ",1929,1968,"Activist","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(6,"Nelson Mandela ",1918,2013,"Politician","Africa");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(7,"Queen Elizabeth II ",1926,2019,"Monarchy","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(8,"Winston Churchill ",1874,1965,"Politician","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(9,"Donald Trump ",1946,2019,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(10,"Bill Gates ",1955,2019,"Business","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(11,"Muhammad Ali ",1942,2016,"Sports","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(12,"Mahatma Gandhi ",1869,1948,"Politician","Asia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(13,"Margaret Thatcher ",1925,2013,"Politician","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(14,"Christopher Columbus ",1451,1506,"Exploration","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(15,"Charles Darwin ",1809,1882,"Scientist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(16,"Elvis Presley ",1935,1977,"Music","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(17,"Albert Einstein ",1879,1955,"Scientist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(18,"Paul McCartney ",1942,2019,"Music","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(19,"Queen Victoria ",1819,1901,"Monarchy","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(20,"Pope Francis ",1936,2019,"Religion","South America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(21,"Jawaharlal Nehru ",1889,1964,"Politician","Asia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(22,"Leonardo da Vinci ",1452,1519,"Artist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(23,"Vincent Van Gogh ",1853,1890,"Artist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(24,"Franklin D. Roosevelt ",1882,1945,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(25,"Pope John Paul II ",1920,2005,"Religion","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(26,"Thomas Edison ",1847,1931,"Scientist","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(27,"Rosa Parks ",1913,2005,"Activist","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(28,"Aung San Suu Kyi ",1945,2019,"Politician","Asia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(29,"Lyndon Johnson ",1908,1973,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(30,"Ludwig Beethoven ",1770,1827,"Music","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(31,"Oprah Winfrey ",1954,2019,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(32,"Indira Gandhi ",1917,1984,"Politician","Asia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(33,"Eva Peron ",1919,1952,"Politician","South America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(34,"Benazir Bhutto ",1953,2007,"Politician","Asia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(35,"George Orwell ",1903,1950,"Author","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(36,"Desmond Tutu ",1931,2019,"Religion","Africa");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(37,"Dalai Lama ",1938,2019,"Religion","Asia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(38,"Walt Disney ",1901,1966,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(39,"Neil Armstrong ",1930,2012,"Scientist","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(40,"Peter Sellers ",1925,1980,"Actor/Actress","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(41,"Barack Obama ",1961,2019,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(42,"Malcolm X ",1925,1965,"Activist","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(43,"J.K.Rowling ",1965,2019,"Author","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(44,"Richard Branson ",1950,2019,"Business","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(45,"Pele ",1940,2019,"Sports","South America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(46,"Angelina Jolie ",1975,2019,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(47,"Jesse Owens ",1913,1980,"Sports","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(48,"Ernest Hemingway ",1899,1961,"Author","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(49,"John Lennon ",1940,1980,"Music","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(50,"Henry Ford ",1863,1947,"Business","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(51,"Haile Selassie ",1892,1975,"Politician","Africa");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(52,"Joseph Stalin ",1879,1953,"Politician","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(54,"Michael Jordon ",1963,2019,"Sports","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(55,"George Bush Jnr ",1946,2019,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(56,"Vladimir Lenin ",1870,1924,"Politician","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(57,"Ingrid Bergman ",1915,1982,"Actor/Actress","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(58,"Fidel Castro ",1926,2019,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(59,"Leo Tolstoy ",1828,1910,"Author","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(60,"Pablo Picasso ",1881,1973,"Artist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(61,"Oscar Wilde ",1854,1900,"Author","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(62,"Coco Chanel ",1883,1971,"Fashion","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(63,"Charles de Gaulle ",1890,1970,"Politician","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(64,"Amelia Earhart ",1897,1937,"Aviation","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(65,"John M Keynes ",1883,1946,"Economist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(66,"Louis Pasteur ",1822,1895,"Scientist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(67,"Mikhail Gorbachev ",1931,2019,"Politician","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(68,"Plato ",-423,-348,"Philosopher","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(69,"Adolf Hitler ",1889,1945,"Politician","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(70,"Sting ",1951,2019,"Music","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(71,"Mary Magdalene ",-4,-40,"Religion","Asia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(72,"Alfred Hitchcock ",1899,1980,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(73,"Michael Jackson ",1958,2009,"Music","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(74,"Madonna ",1958,2019,"Music","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(75,"Mata Hari ",1876,1917,"Politician","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(76,"Cleopatra ",-69,-30,"Monarchy","Africa");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(77,"Grace Kelly ",1929,1982,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(78,"Steve Jobs ",1955,2012,"Business","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(79,"Ronald Reagan ",1911,2004,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(80,"Lionel Messi ",1987,2019,"Sports","South America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(81,"Babe Ruth ",1895,1948,"Sports","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(82,"Bob Geldof ",1951,2019,"Music","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(83,"Leon Trotsky ",1879,1940,"Politician","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(84,"Roger Federer ",1981,2019,"Sports","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(85,"Sigmund Freud ",1856,1939,"Psychology","Australia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(86,"Woodrow Wilson ",1856,1924,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(87,"Mao Zedong ",1893,1976,"Politician","Asia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(88,"Katherine Hepburn ",1907,2003,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(89,"Audrey Hepburn ",1929,1993,"Actor/Actress","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(90,"David Beckham ",1975,2019,"Sports","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(91,"Tiger Woods ",1975,2019,"Sports","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(92,"Usain Bolt ",1986,2019,"Sports","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(93,"Carl Lewis ",1961,2019,"Sports","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(94,"Prince Charles ",1948,2019,"Monarchy","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(95,"Jacqueline Kennedy Onassis ",1929,1994,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(96,"C.S. Lewis ",1898,1963,"Author","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(97,"Billie Holiday ",1915,1959,"Music","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(98,"J.R.R. Tolkien ",1892,1973,"Author","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(99,"Billie Jean King ",1943,2019,"Sports","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(100,"Anne Frank ",1929,1945,"Activist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(101,"Simon Bolivar ",1783,1830,"Activist","South America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(102,"Marie Antoinette ",1755,1793,"Monarchy","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(103,"Cristiano Ronaldo ",1985,2019,"Sports","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(104,"Emmeline Pankhurst  ",1858,1928,"Activist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(105,"Emile Zatopek ",1922,2000,"Sports","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(106,"Lech Walesa ",1943,2019,"Activist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(107,"Julie Andrews ",1935,2019,"Music","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(108,"Florence Nightingale ",1820,1910,"Medicine","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(109,"Marie Curie ",1867,1934,"Scientist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(110,"Stephen Hawking ",1942,2019,"Scientist","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(111,"Tim Berners Lee ",1955,2019,"Technology","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(112,"Lance Armstrong ",1971,2019,"Sports","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(113,"Shakira ",1977,2019,"Music","South America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(114,"Jon Stewart ",1962,2019,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(115,"Orville Wright",1871,1948,"Inventor","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(116,"Wilbur Wright",1867,1912,"Inventor","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(117,"Roman Abramovich ",1966,2019,"Business","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(118,"Tom Cruise ",1962,2019,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(119,"Rupert Murdoch ",1931,2019,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(120,"Al Gore ",1948,2019,"Politician","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(121,"Sacha Baron Cohen ",1971,2019,"Actor/Actress","Europe");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(122,"George Clooney ",1961,2019,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(123,"Paul Krugman ",1953,2019,"Economist","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(124,"Jimmy Wales ",1966,2019,"Technology","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(125,"Brad Pitt ",1963,2019,"Actor/Actress","North America");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(126,"Kylie Minogue ",1968,2019,"Music","Australia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(127,"Malala Yousafzai ",1997,2019,"Activist","Asia");
INSERT INTO history(Id, Name, Birth, Death, Width, Category, Location) VALUES(128,"Stephen King ",1947,2019,"Author","North America");